### ISSUE TITLE
plugin是干嘛用的？

### ISSUE THREAD

**Issue by jan4984** [guonaihong/threadpool#1]
这个plugin有啥用？能不能给个实际的例子？

**Comment by guonaihong** [comment]
plugin主要是实现是一套钩子函数，可见tp_vtable_t类型，方便写代码。
```c
struct tp_vtable_t {
    int  (*global_init)(tp_vtable_global_arg_t *g);   //定义了一个进程只初始化一次的函数

    int  (*create)(tp_vtable_child_arg_t *c);         //定义了一个线程只运行一次的函数
    int  (*process)(tp_vtable_child_arg_t *c);        //线程的运行主体函数
    void (*destroy)(tp_vtable_child_arg_t *c);        //线程退出时会运行的函数

    void (*global_destroy)(tp_vtable_global_arg_t *g);//进程退出时会调用的函数
};
```


如果你的业务里有，某个函数一个进程只要初始化一次，某个函数一个线程只要初始化一次。
有运行时的函数，线程退出自动调用退出函数，进程退出自动资源销毁的函数。

比如语言识别的引擎，这是一个比较好的应用场景，把此类函数填充此tp_plugin_t，应层只要实现tcp通信，就可以把此类引擎包装成一个tcp层面的服务。

[线程池plugin使用示例](https://github.com/guonaihong/threadpool/blob/master/tests/pool_echo_serve.c)

**Comment by jan4984** [comment]
那producer和consumer有啥区别？

**Comment by guonaihong** [comment]
plugin分为生产者和消费者的原因是:

- 

把一个任务拆分成生产者和消费者是一个很自然的想法，特别是服务端。
如果说，accept是生产者，那么处理accept之后的fd就是消费者要做的事情。

- 

在plugin层面保证生产者优先于消费者前面执行，他们的区别主要是顺序的区别。

**Comment by jan4984** [comment]
嗯，有一定道理。不过，如果tp里面还要分group的话，我可能会考虑用多个tp。或者要么加一个统一的group机制？可以给tp分N个group，每个groupd有优先级。
