### ISSUE TITLE
echo_server测试不通过，停在producer_global_destroy不动了

### ISSUE THREAD

**Issue by jan4984** [guonaihong/threadpool#2]
./tests/pool_echo_serve
server_pool create ok
[echo client] [2017-03-30 16:26:45.942] [INFO ] producer_global_init
[echo client] [2017-03-30 16:26:45.942] [INFO ] producer_create
[echo client] [2017-03-30 16:26:45.942] [INFO ] run process start user data:producer create ok
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676537849600:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676529395456:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676520941312:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676512487168:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676504033024:consumer_process
send echo_client (98) timeout
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676495578880:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676487124736:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676478670592:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676470216448:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676461762304:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676453308160:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676444854016:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676436399872:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676427945728:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676419491584:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676411037440:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676402583296:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676394129152:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676385675008:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676377220864:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676368766720:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676360312576:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676351858432:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676343404288:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676334950144:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676326496000:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676318041856:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676309587712:consumer_process
[echo client] [2017-03-30 16:26:45.942] [INFO ] 139676546303744:consumer_process
[echo client] [2017-03-30 16:26:51.459] [WARN ] accept_timedwait timeout
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676461762304:consumer_process:id(1490862405979211400) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676351858432:consumer_process:id(1490862405975473400) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676520941312:consumer_process:id(1490862405975701600) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676419491584:consumer_process:id(1490862405972026000) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676487124736:consumer_process:id(1490862405976040700) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676343404288:consumer_process:id(1490862405976048600) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676537849600:consumer_process:id(1490862405976361200) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676385675008:consumer_process:id(1490862405976494300) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676427945728:consumer_process:id(1490862405973530000) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676512487168:consumer_process:id(1490862405976830600) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676334950144:consumer_process:id(1490862405976836900) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676436399872:consumer_process:id(1490862405977045300) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676529395456:consumer_process:id(1490862405977171200) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676453308160:consumer_process:id(1490862405974080600) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676478670592:consumer_process:id(1490862405977566000) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676377220864:consumer_process:id(1490862405974184500) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676326496000:consumer_process:id(1490862405977874700) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676368766720:consumer_process:id(1490862405977959200) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676504033024:consumer_process:id(1490862405974775400) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676318041856:consumer_process:id(1490862405978243800) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676470216448:consumer_process:id(1490862405978365800) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676394129152:consumer_process:id(1490862405978618800) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676309587712:consumer_process:id(1490862405978925600) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676411037440:consumer_process:id(1490862405978972900) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676444854016:consumer_process:id(1490862405979068500) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676402583296:consumer_process:id(1490862406459351800) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676546303744:consumer_process:id(1490862405979271400) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676495578880:consumer_process:id(1490862405972806000) shutdown
[echo client] [2017-03-30 16:26:51.459] [INFO ] 139676360312576:consumer_process:id(1490862406459504600) shutdown
[echo client] [2017-03-30 16:26:51.464] [INFO ] producer_global_destroy

**Comment by jan4984** [comment]
我是在win10的subsystem for linux里面编译运行的

**Comment by jan4984** [comment]
8分钟以后退出来了....

**Comment by guonaihong** [comment]
- 回答下为什么退出这么慢

线程退出是缓慢进行的。

- 背后的想法:

主要是设想生产环境，一开始创建了很多线程，如果很快回收，再来一波大流量，再创建很多线程，感觉没必须。还不如缓慢回收呢。
我下次在终端打印个日志，写道，线程全部回收大约需要xxx时间。
